[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "chromium", "nss", "freetype", "harfbuzz", "cacert"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["cd backend && npm install && npm run build"]

[start]
cmd = "cd backend && npm start"

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/nix/store"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
