[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "ttf-dejavu"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["cd backend && npm install && npm run build"]

[start]
cmd = "cd backend && npm start"

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/nix/store"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
